# Site settings
name: HC is on the way.
email: lhch35@126.com
author: HC
url: 
resume_site: 
github: 
baseurl: ""
description: Glory is fleeting.
meta_description: HC;个人博客;
motto: Glory is fleeting.
encoding: utf-8
banner: Tech

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: EcoRIIHC
highlighter: rouge

# Build settings
markdown: kramdown

# FB:
#   comments :
#     provider : disqus
#     duoshuo:
#         short_name : HCare
#     disqus :
#         short_name : disqushc
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light

gems: [jekyll-paginate]